Add streamcopy testing to the autopkgtest.

diff --git a/debian/tests/encdec b/debian/tests/encdec
--- a/debian/tests/encdec
+++ b/debian/tests/encdec
@@ -62,7 +62,7 @@ encode_file() {
     fi
     echo -e "trying muxer '$mux' with '$type' encoder '$encoder' for codec '$codec'\n"
     ret=0
-    CMD="ffmpeg -f lavfi -i $src -strict -2 $opts -c:$type $encoder -f $mux $file_name -y -hide_banner"
+    CMD="ffmpeg -f lavfi -i $src -strict -2 $opts -c:$type $encoder -f $mux $file_name -y -hide_banner -nostdin"
     echo $CMD
     $CMD 2>&1 || ret=$?
     return $ret
@@ -119,7 +119,20 @@ decode_file() {
     file_name=$1
     ret=0
     # The option '-t 1' is necessary, because the comfortnoise decoder never stops producing noise.
-    CMD="ffmpeg -strict -2 -i $file_name -t 1 -c:v rawvideo -c:a pcm_s32le -f nut /dev/null -y -hide_banner"
+    CMD="ffmpeg -strict -2 -i $file_name -t 1 -c:v rawvideo -c:a pcm_s32le -f nut /dev/null -y -hide_banner -nostdin"
+    echo $CMD
+    $CMD 2>&1 || ret=$?
+    return $ret
+}
+
+streamcopy_file() {
+    file_name=$1
+    test=$2
+    mux=${test%%;*}
+    file_name_copy="$file_name.copy.$mux"
+    ret=0
+    # The option '-t 1' is necessary, because the comfortnoise decoder never stops producing noise.
+    CMD="ffmpeg -strict -2 -i $file_name -t 1 -c copy -f $mux $file_name_copy -y -hide_banner -nostdin"
     echo $CMD
     $CMD 2>&1 || ret=$?
     return $ret
@@ -274,6 +287,11 @@ num_success=0
 for test in $tests; do
     num_test=$((num_test + 1))
     echo "Test $num_test:"
+    streamcopy=${test##*|}
+    if [ "$update" ]; then
+        streamcopy=1
+    fi
+    test=${test%%|*}
     # skip the test, if the muxer/encoder is not available
     available=$(echo "$possible_tests" | grep " $test ") || true
     if [ ! "$available" ]; then
@@ -324,7 +342,40 @@ for test in $tests; do
         echo -e "FAILED: $errmsg\n\n"
         continue
     fi
-    echo -e "\nSUCCESS: correctly created file with format '$mux' and codec '$tenc'\n\n"
+    if [ "$streamcopy" == "1" ]; then
+        ret=0
+        # test streamcopying the file
+        # this also sets the file_name_copy variable
+        echo -e "\n"
+        streamcopy_file "$file_name" "$test" || ret=$?
+        if [ "$ret" != "0" ]; then
+            errmsg="$test; streamcopy return code: $ret"
+            if [ "$ret" -gt 128 ]; then
+                crashes="${crashes}${errmsg}\n"
+            else
+                failures="${failures}${errmsg}\n"
+            fi
+            echo -e "FAILED: $errmsg\n\n"
+            streamcopy=0
+        fi
+    fi
+    if [ "$streamcopy" == "1" ]; then
+        ret=0
+        # test if the file has the correct format/codec
+        err=$(probe_file "$file_name_copy" $test) || ret=$?
+        if [ "$ret" != "0" ]; then
+            errmsg="$test; streamcopy: $err"
+            if [ "$ret" -gt 128 ]; then
+                crashes="${crashes}${errmsg}\n"
+            else
+                failures="${failures}${errmsg}\n"
+            fi
+            echo -e "FAILED: $errmsg\n\n"
+            streamcopy=0
+        fi
+    fi
+    works=$([ "$streamcopy" = "1" ] && echo works || echo fails)
+    echo -e "\nSUCCESS: correctly created file with format '$mux' and codec '$tenc'; streamcopying $works\n\n"
     num_success=$((num_success + 1))
     if [ "$update" ]; then
         if [ "x$last_mux" != "x$mux" ]; then
@@ -335,7 +386,7 @@ for test in $tests; do
             echo -n "$mux;" >> $ENCDECLIST
         fi
         last_mux=$mux
-        echo -n " $tenc" >> $ENCDECLIST
+        echo -n " $tenc|$streamcopy" >> $ENCDECLIST
     fi
 done
 
